npm i node-superfetch
npm i quick.db
npm i ms
npm i moment-duration-format
npm i node-superfetch
npm i common-tags
npm i snekfetch
npm i user-instagram
npm i quick.db
npm i lowdb
npm i lowdb
 npm i x
npm i humanize-duration
npm i simple-youtube-api
npm i ytdl-core
npm i hastebin-gen
npm i hastebin-gen
npm i discord.js
npm i quick.db
npm i nodme
npm i nodme
npm i chalk
npm i snekfetch
npm i canvas
npm i canvas-constructor
npm i canvas-node
npm i discord.js
